### ISSUE TITLE
always logs in to home page

### ISSUE THREAD

**Issue by pjv** [blockvis/civic-sip-wp#2]
It appears that even if the URL that you are logging into in WP has a redirect to some specific page, if you log in via Civic the plugin disregards the intended destination address and puts the user on the home page of the WP site.

e.g. if you are not logged in and you go to `https://example.com/wp-admin` the WP site will re-direct you to `https://example.com/wp-login.php?redirect_to=https%3A%2F%2Fexample.com%2Fwp-admin%2F&reauth=1`. If you do a normal WP login, then you end up in the WP dashboard at `https://example.com/wp-admin/`. But if you log in with Civic, you end up at `https://example.com/`.

**Comment by cheelahim** [comment]
Hey @pjv. Thank you for bringing this up.  I agree the plugin should respect the the intended URL. We will fix this issue in following release.

**Comment by cheelahim** [comment]
Hey @pjv. We made some changes to respect the intended URL and redirect after successful login. This patch is included in 1.1.2 release.

**Comment by pjv** [comment]
@cheelahim Great - I'll look forward to it. Thanks.
