### ISSUE TITLE
Can't stay logged in

### ISSUE THREAD

**Issue by pjv** [blockvis/civic-sip-wp#3]
The login cookie that the plugin creates always expires with the session. The normal WP login has a "keep me logged in" checkbox that writes a cookie that expires in two weeks. Even if you check that box before executing the Civic login, it still writes a session cookie.

It would be good if the plugin could respect the "keep me logged in" checkbox.

**Comment by cheelahim** [comment]
Hey @pjv . This is one less straightforward. Since developers are free to put the short-code wherever they want, the users are not necessarily logging in from 'wp-login' page, hence might not see this checkbox.  We  need to investigate this to come up with consistent solution.

**Comment by pjv** [comment]
Hi @cheelahim - yeah, i see the issue. I don't think this is really a big deal, but it would be nice to be able to support the standard "remember me" functionality.

Here's the code around the "remember me" checkbox in the standard WP login form:
<img width="566" alt="2017-10-22 at 10 48 am" src="https://user-images.githubusercontent.com/327716/31863694-c2a23af4-b716-11e7-8c69-85989b4521f5.png">

What if you modified the Civic shortcode to output a similar checkbox with the same name/id `rememberme` and then modify the code that processes a click on the Civic login button (either on the standard login page or on another page via the shortcode) so that it takes the value of that checkbox input into account?

**Comment by cheelahim** [comment]
@pjv I agree it is a nice to have feature but we should avoid breaking changes too. Rendering new elements with current short-code could break existing installations. We will check how other vendors (if any) deal with this functionality in their auth plugins.

**Comment by Zorato** [comment]
Added support of remember me flag from sign in form at wp-login.php in [4b95db3](https://github.com/blockvis/civic-sip-wp/commit/4b95db34dd2edbd47933607611695a5fc2b09549). Fix is going to be delivered with 1.1.2 release.
