### ISSUE TITLE
PHPASN1 Dependency not compatible with PHP 7.2

### ISSUE THREAD

**Issue by WesleyJohnson** [blockvis/civic-sip-wp#5]
It looks like Civic is dependent on PHPASN1 and is referencing a development version of that project. That development version is incompatible with PHP 7.2 and is throwing this exception:

`[17-Apr-2018 02:50:00 UTC] PHP Fatal error:  Cannot use FG\ASN1\Object as Object because 'Object' is a special class name in /home/c2l2018io/public_html/wp-content/plugins/civic-sip/includes/vendor/mdanter/ecc/src/Serializer/PrivateKey/DerPrivateKeySerializer.php on line 5`

The issue is referenced on the PHPASN1 repo at the link below and a fix was eventually merged in. Could Civic be updated to the latest release of PHPASN1 to resolve this issue?

https://github.com/fgrosse/PHPASN1/issues/65

**Comment by cheelahim** [comment]
Hi @WesleyJohnson. Thank you for reporting the issue. We haven't been actively updating the plugin for some time now. So it will take us some time to fix this issue and roll out the plugin update. We have a requirement to keep PHP 5.6 compatibility as long as possible, therefore pulling new libraries is a slow process for us. I need to check but I believe the API client library has received the required update blockvis/civic-sip-php#2, if so we should be able to update the plugin relatively safe. I think we will be able to release the plugin update this week. Will do my best to speed up the process though.

**Comment by WesleyJohnson** [comment]
Thank you very much, @cheelahim!

**Comment by C2Legacy** [comment]
@cheelahim do you have any update on the ETA for completion?

**Comment by cheelahim** [comment]
@C2Legacy We updated the dependencies. We're testing backward compatibility with PHP 5.6. 
If everything is fine, you may expect the new release within 24 hours.

**Comment by cheelahim** [comment]
@WesleyJohnson @C2Legacy  We've updated the plugin over weekend. You can try new 2.0 release by downloading this repository and updating the plugin manually. Please report any compatibility issues.

**Comment by pjv** [comment]
Version 2.0 still incompatible with PHP 7.2. The `phpasn1` library is declaring a class name `Object` and PHP 7.2 does not allow it.

Error message from debug log:

`[26-Apr-2018 13:12:24 UTC] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /var/www/example.com/htdocs/wp-content/plugins/civic-sip/includes/vendor/fgrosse/phpasn1/lib/ASN1/Object.php on line 43`

**Comment by WesleyJohnson** [comment]
The PHPASN1 library was already updated to fix this issue. I thought part
of the civic-sip-wip 2.0 update was to update the dependencies so grab the
new version of PHPASN1?

https://github.com/fgrosse/PHPASN1/pull/66

**Comment by pjv** [comment]
seems like you guys should pull in some updates. Especially since v. 2.0 of this plugin declares a minimum version of PHP 7.0.

<img width="649" alt="2018-04-26 at 10 24 am" src="https://user-images.githubusercontent.com/327716/39315325-0d2f3b5a-493c-11e8-98ec-52c47ea4ee0a.png">

**Comment by cheelahim** [comment]
@WesleyJohnson @pjv Thank you for your help. For some reason part of the dependencies were stalled. Now we've updated the whole dependency tree. The release 2.0.2 should have the latest changes to fix the issue. Please verify.

**Comment by pjv** [comment]
working for me. 👍

**Comment by cheelahim** [comment]
@WesleyJohnson any update from your side? Did the latest patch resolve your issues too?

**Comment by WesleyJohnson** [comment]
@cheelahim My apologies on the delay in responding. After updating to the 2.0.2 version we were still having some issues with an authorization error. After trying to reinstall the plugin and continuing to have issues, I finally created a new Application on the Civic Integration Portal and updated the plugin to use the various keys and settings for the new application. After making those changes, the plugin started working perfectly. I'm hoping it wasn't a configuration issue this whole time, but at any rate it's working now and we're pleased. :)

Thanks!
